name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
          sudo apt-get install -y libgc-dev cmake ninja-build pybind11-dev
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine_1.20.0_amd64.deb
          sudo dpkg -i hyperfine_1.20.0_amd64.deb
          sudo curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
          uv pip install -U nanobind
          uv pip install -U pybind11

      - name: Build
        run: |
          ./build_mlir.sh
          ./vendor_mlir.sh
          ./build.sh
          cmake --build build

      - name: Hello
        run: |
          ./build/bin/lyc jit examples/hello.py
          ./build/bin/lyc jit examples/oop.py

      - name: Benchmarks
        run: |
          ./build/bin/lyc examples/fib.py -o fib_aot
          ./build/bin/lyc examples/fib_prim.py -o fib_prim_aot
          hyperfine -w 1 -r 5 "python3 examples/fib.py" "./build/bin/lyc jit examples/fib.py" "./fib_aot" "./fib_prim_aot"
